# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ocelotconsulting.com
title: Ocelot Consulting
email: info@ocelotconsulting.com
author: Ocelot Developers
description: > # "Ocelot Consulting specializes in Cloud technologies, custom application development and enterprise security.
  Ocelot Consultants are certified AWS Solution Architects and have experience migrating enterprise applications and data for
  Fortune 500 companies.
copyright: 'Copyright &copy; 2016 Ocelot Consulting LLC. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ocelot_llc
  - title: github
    url: https://github.com/ocelotconsulting/
  - title: linkedin
    url: https://www.linkedin.com/company/ocelot-consulting-llc
  - title: facebook
    url: https://facebook.com/ocelotconsultingllc/

# Team names, titles and social links
people:
- name: Larry Anderson
  pic: 1
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
