# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ocelotconsulting.com
title: Ocelot Consulting
email: info@ocelotconsulting.com
author: Ocelot Developers
description: > # "Ocelot Consulting specializes in cloud technologies, custom application development and enterprise security.
  Ocelot Consultants are certified AWS Solution Architects and have experience migrating enterprise applications and data for
  Fortune 500 companies.
copyright: 'Copyright &copy; 2016 Ocelot Consulting LLC. All Rights Reserved.'

about: 'Ocelot Consulting specializes in cloud technologies, custom application development and enterprise security.
Ocelot Consultants are certified AWS Solution Architects and have experience migrating enterprise applications and data for
Fortune 500 companies.'
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ocelot_llc
  - title: github
    url: https://github.com/ocelotconsulting/
  - title: linkedin
    url: https://www.linkedin.com/company/ocelot-consulting-llc
  - title: facebook
    url: https://facebook.com/ocelotconsultingllc/

# Team names, titles and social links
people:
- name: Tyler Robert
  pic: tyler
  position: Co-Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/tyler-robert
    - title: github
      url: https://github.com/tylerrobert

- name: Larry Anderson
  pic: larry
  position: Co-Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/larryanderson
    - title: github
      url: https://github.com/larryboymi
    - title: stack-overflow
      url: http://stackoverflow.com/users/1380238/larry-anderson

- name: John O'Malley
  pic: john
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Chris Coffman
  pic: chris
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
